import fs from 'node:fs';
import path from 'node:path';
import { afterAll, describe, expect, it } from 'vitest';
import { cleanMessageText, extractText, isHarnessNoise, readSessionFile, stripSystemReminders } from '../src/core/parser.js';
import { aiTitle, assistantMessage, cleanupTempDirs, makeFixture, userMessage, writeSession } from './helpers.js';

afterAll(cleanupTempDirs);

describe('text extraction (criterion 4)', () => {
  it('keeps string content as-is', () => {
    expect(extractText('hello there')).toBe('hello there');
  });

  it('keeps only text blocks from arrays', () => {
    const content = [
      { type: 'text', text: 'first' },
      { type: 'thinking', thinking: 'secret reasoning' },
      { type: 'tool_use', name: 'Bash', input: { command: 'ls' } },
      { type: 'tool_result', content: 'file listing' },
      { type: 'image', source: {} },
      { type: 'text', text: 'second' },
    ];
    expect(extractText(content)).toBe('first\nsecond');
  });

  it('strips multiline system-reminder blocks', () => {
    const raw = 'before\n<system-reminder>\nhidden\nlines\n</system-reminder>\nafter';
    expect(stripSystemReminders(raw)).toBe('before\n\nafter');
  });

  it('drops messages that are only a system reminder', () => {
    expect(cleanMessageText('<system-reminder>only this</system-reminder>')).toBeNull();
  });

  it.each([
    '<command-name>/clear</command-name>',
    '<command-message>doing a thing</command-message>',
    '<local-command-stdout>output</local-command-stdout>',
    '<local-command-stderr>err</local-command-stderr>',
    '<task-notification>done</task-notification>',
    '<bash-input>ls</bash-input>',
    '<bash-stdout>a b c</bash-stdout>',
    'Caveat: The messages below were generated by the user while running local commands. Blah.',
  ])('treats %s as harness noise', (text) => {
    expect(isHarnessNoise(text)).toBe(true);
    expect(cleanMessageText(text)).toBeNull();
  });
});

describe('session parsing', () => {
  it('uses the cwd from the record, never the encoded directory name (criterion 3)', async () => {
    const fixture = makeFixture();
    // Encoded name is lossy: both "/" and a real "-" collapse to "-".
    const file = writeSession(fixture.projectsDir, '-tmp-my-cool-app', 'sess-dash', [
      userMessage('hello from a dashed folder', { cwd: '/tmp/my-cool-app' }),
    ]);
    const parsed = await readSessionFile(file);
    expect(parsed?.meta.cwd).toBe('/tmp/my-cool-app');
  });

  it('prefers the last ai-title and falls back to the first human message', async () => {
    const fixture = makeFixture();
    const titled = writeSession(fixture.projectsDir, '-tmp-a', 'titled', [
      userMessage('first human message'),
      aiTitle('Early title'),
      assistantMessage('sure'),
      aiTitle('Final title'),
    ]);
    expect((await readSessionFile(titled))?.meta.title).toBe('Final title');

    const untitled = writeSession(fixture.projectsDir, '-tmp-a', 'untitled', [
      assistantMessage('assistant speaks first'),
      userMessage('the human question about recording videos'),
    ]);
    expect((await readSessionFile(untitled))?.meta.title).toBe('the human question about recording videos');
  });

  it('skips sidechain, meta, empty and noisy records (criterion 4)', async () => {
    const fixture = makeFixture();
    const file = writeSession(fixture.projectsDir, '-tmp-a', 'filtered', [
      userMessage('keep this one'),
      userMessage('sidechain text', { isSidechain: true }),
      userMessage('meta text', { isMeta: true }),
      userMessage([{ type: 'tool_result', content: 'tool result text' }]),
      userMessage([{ type: 'thinking', thinking: 'thinking text' }]),
      userMessage('<system-reminder>reminder text</system-reminder>'),
      userMessage('<bash-input>ls</bash-input>'),
      assistantMessage([{ type: 'text', text: 'and this one' }]),
    ]);
    const parsed = await readSessionFile(file);
    expect(parsed?.messages.map((m) => m.text)).toEqual(['keep this one', 'and this one']);
  });

  it('survives a truncated last line and garbage lines (criterion 5)', async () => {
    const fixture = makeFixture();
    const file = writeSession(
      fixture.projectsDir,
      '-tmp-a',
      'ragged',
      [userMessage('first good message'), assistantMessage('second good message')],
      ['not json at all', '{"type":"user","message":{"role":"user","content":"truncat'],
    );
    const parsed = await readSessionFile(file);
    expect(parsed?.messages.map((m) => m.text)).toEqual(['first good message', 'second good message']);
  });

  it('returns null when there is no indexable record', async () => {
    const fixture = makeFixture();
    const file = writeSession(fixture.projectsDir, '-tmp-a', 'empty', [
      { type: 'mode', mode: 'default' },
      aiTitle('A title with no messages'),
    ]);
    expect(await readSessionFile(file)).toBeNull();
  });

  it('returns null when no record carries a cwd', async () => {
    const fixture = makeFixture();
    const dir = path.join(fixture.projectsDir, '-tmp-a');
    fs.mkdirSync(dir, { recursive: true });
    const file = path.join(dir, 'nocwd.jsonl');
    fs.writeFileSync(
      file,
      `${JSON.stringify({ type: 'user', uuid: 'u1', timestamp: '2026-01-01T00:00:00.000Z', message: { role: 'user', content: 'orphan' } })}\n`,
    );
    expect(await readSessionFile(file)).toBeNull();
  });
});
