import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import { sanitizeLine, sanitizeText } from './sanitize.js';

/** Role of an indexed message. */
export type Role = 'user' | 'assistant';

/** One indexable message extracted from a transcript. */
export interface ParsedMessage {
  uuid: string;
  role: Role;
  /** ISO timestamp as written by Claude Code. Empty string if absent. */
  ts: string;
  /** Cleaned plain text. Never empty. */
  text: string;
}

/** Session-level metadata derived from a transcript file. */
export interface ParsedSessionMeta {
  sessionId: string;
  /** Real working directory, taken from a record, never decoded from the directory name. */
  cwd: string;
  title: string;
  gitBranch: string;
  firstTs: string;
  lastTs: string;
  messageCount: number;
}

export interface ParseOptions {
  /** Overrides the session id derived from the file name. */
  sessionId?: string | undefined;
  /** Called for every indexable message, in file order, while streaming. */
  onMessage?: ((message: ParsedMessage, index: number) => void) | undefined;
}

const SYSTEM_REMINDER_RE = /<system-reminder>[\s\S]*?<\/system-reminder>/g;

const HARNESS_PREFIXES = [
  '<command-name>',
  '<command-message>',
  '<local-command-stdout>',
  '<local-command-stderr>',
  '<task-notification>',
  '<bash-input>',
  '<bash-stdout>',
  'Caveat: The messages below were generated by the user while running local commands',
];

/** Removes `<system-reminder>…</system-reminder>` blocks (multiline) and trims. */
export function stripSystemReminders(text: string): string {
  return text.replace(SYSTEM_REMINDER_RE, '').trim();
}

/** True when the cleaned text is harness noise rather than something a human or Claude said. */
export function isHarnessNoise(text: string): boolean {
  return HARNESS_PREFIXES.some((prefix) => text.startsWith(prefix));
}

/**
 * Pulls plain text out of `message.content`. A string is used as-is; an array
 * keeps only `type === "text"` blocks joined with newlines. `tool_use`,
 * `tool_result`, `thinking` and `image` blocks are ignored.
 */
export function extractText(content: unknown): string {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  const parts: string[] = [];
  for (const block of content) {
    if (block && typeof block === 'object') {
      const b = block as { type?: unknown; text?: unknown };
      if (b.type === 'text' && typeof b.text === 'string') parts.push(b.text);
    }
  }
  return parts.join('\n');
}

/**
 * Cleans raw content and returns null when the message should not be indexed.
 *
 * The text is sanitised here, at the boundary, because this is the string that
 * gets stored: FTS5 offsets and therefore every highlight range index into the
 * sanitised form.
 */
export function cleanMessageText(content: unknown): string | null {
  const raw = extractText(content);
  if (raw.length === 0) return null;
  const cleaned = sanitizeText(stripSystemReminders(raw)).trim();
  if (cleaned.length === 0) return null;
  if (isHarnessNoise(cleaned)) return null;
  return cleaned;
}

/** Session id from `<encoded-cwd>/<sessionId>.jsonl`. */
export function sessionIdFromPath(filePath: string): string {
  return path.basename(filePath, '.jsonl');
}

/**
 * Streams one `.jsonl` transcript line by line (the file is never read whole
 * into memory) and reports every indexable message through
 * `options.onMessage`.
 *
 * Returns null when the file holds no indexable `user`/`assistant` record with
 * an absolute `cwd`, which means the session must be skipped.
 *
 * Malformed lines, including a truncated final line, are skipped silently.
 */
export async function parseSessionFile(
  filePath: string,
  options: ParseOptions = {},
): Promise<ParsedSessionMeta | null> {
  const sessionId = options.sessionId ?? sessionIdFromPath(filePath);
  const onMessage = options.onMessage;

  let cwd = '';
  let gitBranch = '';
  let aiTitle = '';
  let fallbackTitle = '';
  let firstTs = '';
  let lastTs = '';
  let count = 0;

  const stream = fs.createReadStream(filePath, { encoding: 'utf8' });
  const rl = readline.createInterface({ input: stream, crlfDelay: Infinity });

  try {
    for await (const line of rl) {
      if (line.length === 0) continue;
      let record: unknown;
      try {
        record = JSON.parse(line);
      } catch {
        continue; // malformed or truncated line
      }
      if (!record || typeof record !== 'object' || Array.isArray(record)) continue;
      const rec = record as Record<string, unknown>;

      if (rec['type'] === 'ai-title') {
        if (typeof rec['aiTitle'] === 'string') {
          const cleaned = sanitizeLine(rec['aiTitle']).trim();
          if (cleaned.length > 0) aiTitle = cleaned; // the LAST one wins
        }
        continue;
      }

      const type = rec['type'];
      if (type !== 'user' && type !== 'assistant') continue;
      if (rec['isSidechain'] === true) continue;
      if (rec['isMeta'] === true) continue;

      const message = rec['message'];
      if (!message || typeof message !== 'object') continue;
      const text = cleanMessageText((message as Record<string, unknown>)['content']);
      if (text === null) continue;

      // A transcript can claim any cwd, including "." or "~/x". Only an
      // absolute path may become the folder the tool would `cd` into, so a
      // forged relative cwd can never point at the launch directory.
      if (cwd === '' && typeof rec['cwd'] === 'string') {
        const candidate = sanitizeLine(rec['cwd']).trim();
        if (candidate.length > 0 && path.isAbsolute(candidate)) cwd = candidate;
      }
      if (typeof rec['gitBranch'] === 'string') {
        const branch = sanitizeLine(rec['gitBranch']).trim();
        if (branch.length > 0) gitBranch = branch;
      }

      const ts = typeof rec['timestamp'] === 'string' ? rec['timestamp'] : '';
      if (ts !== '') {
        if (firstTs === '' || ts < firstTs) firstTs = ts;
        if (ts > lastTs) lastTs = ts;
      }

      const role: Role = type === 'user' ? 'user' : 'assistant';
      if (fallbackTitle === '' && role === 'user') {
        fallbackTitle = text.replace(/\s+/g, ' ').trim().slice(0, 80);
      }

      const uuid = typeof rec['uuid'] === 'string' ? sanitizeLine(rec['uuid']) : `${sessionId}:${count}`;
      onMessage?.({ uuid, role, ts, text }, count);
      count += 1;
    }
  } finally {
    rl.close();
    stream.destroy();
  }

  if (count === 0 || cwd === '') return null;

  const title = aiTitle !== '' ? aiTitle : fallbackTitle !== '' ? fallbackTitle : '(untitled session)';
  return { sessionId, cwd, title, gitBranch, firstTs, lastTs, messageCount: count };
}

/** Convenience wrapper that buffers the messages. Handy in tests and small tools. */
export async function readSessionFile(
  filePath: string,
  options: Omit<ParseOptions, 'onMessage'> = {},
): Promise<{ meta: ParsedSessionMeta; messages: ParsedMessage[] } | null> {
  const messages: ParsedMessage[] = [];
  const meta = await parseSessionFile(filePath, {
    ...options,
    onMessage: (m) => messages.push(m),
  });
  if (!meta) return null;
  return { meta, messages };
}
